services:

  db: 
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - back-end/.env
    volumes:
      - pg:/var/lib/lib/postgressql/data

  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 2500:5000
    depends_on:
      - db
    env_file:
      - back-end/.env
    
  react_app:
    container_name: react_app
    build: ./front-end
    volumes:
      - build_react:/var/www/html
    
  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_reat:/var/www/html
    depends_on:
      - db
      - node_app
      - react_app
  
volumes: 
  pg:
  build_react: